name: catinder
description: "Flutter project about cats."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  intl: any
  dio: ^5.8.0
  provider: ^6.1.2
  flutter_launcher_icons: ^0.13.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/program-icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/like.png
    - assets/icons/dislike.png
    - assets/sad-cat.jpg

